# Generated by Django 2.1.8 on 2019-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_missinform'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinform',
            name='gender',
            field=models.CharField(default='O', max_length=5),
            preserve_default=False,
        ),
    ]
