# Generated by Django 2.1.8 on 2019-04-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_missinform_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinform',
            name='city',
            field=models.CharField(default='서울', max_length=20),
            preserve_default=False,
        ),
    ]
